#! /bin/sh

# Killing any possible previous processes
killall -q picom
killall -q sxhkd
killall -q polybar
killall -q xwinwrap

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
picom &
polybar -c=~/.config/polybar/bar mybar &

# set your resolution on the g flag
xwinwrap -ov -g 1920x1080+0+0 -- mpv -wid WID ~/wallpapers/wallpaper.mp4 --no-osc --no-osd-bar --loop-file --player-operation-mode=cplayer --no-audio --panscan=1.0 --no-input-default-bindings &

# Monitors
bspc monitor -d 1 2 3 4 5 6 7

# Mouse configs
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

# Settings
bspc config focused_border_color    "#f79b31"  
bspc config normal_border_color     "#162447"

bspc config top_padding         20
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
